CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE castles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    color VARCHAR(50)
);

CREATE TABLE heroes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    castle_id UUID REFERENCES castles(id),
    specialization VARCHAR(100),
    attack INTEGER DEFAULT 0,
    defense INTEGER DEFAULT 0,
    power INTEGER DEFAULT 0,
    knowledge INTEGER DEFAULT 0,
    starting_spell VARCHAR(100)
);

CREATE TABLE creatures (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    level INTEGER NOT NULL,
    attack INTEGER NOT NULL,
    defense INTEGER NOT NULL,
    damage_min INTEGER NOT NULL,
    damage_max INTEGER NOT NULL,
    health INTEGER NOT NULL,
    speed INTEGER NOT NULL,
    growth INTEGER NOT NULL,
    cost_gold INTEGER NOT NULL,
    cost_resource VARCHAR(100),
    castle_id UUID REFERENCES castles(id)
);

CREATE TABLE artifacts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    slot VARCHAR(50) NOT NULL,
    description TEXT,
    attack_bonus INTEGER DEFAULT 0,
    defense_bonus INTEGER DEFAULT 0,
    power_bonus INTEGER DEFAULT 0,
    knowledge_bonus INTEGER DEFAULT 0,
    rarity VARCHAR(50)
);

CREATE TABLE spells (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    school VARCHAR(50) NOT NULL,
    level INTEGER NOT NULL,
    cost INTEGER NOT NULL,
    description TEXT
);

CREATE TABLE skills (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    category VARCHAR(50)
);

INSERT INTO castles (name, description, color) VALUES
('Замок', 'Замок людей - символ порядка и справедливости', 'Синий'),
('Оплот', 'Оплот эльфов - защитники природы', 'Зеленый'),
('Башня', 'Башня волшебников - центр магии', 'Красный'),
('Инферно', 'Инферно демонов - воплощение хаоса', 'Красный'),
('Некрополис', 'Некрополис нежити - власть над смертью', 'Черный'),
('Подземелье', 'Подземелье темных эльфов - тени и интриги', 'Фиолетовый'),
('Крепость', 'Крепость варваров - сила и ярость', 'Оранжевый'),
('Цитадель', 'Цитадель гномов - мастерство и упорство', 'Коричневый'),
('Убежище', 'Убежище элементалей - гармония стихий', 'Бирюзовый');

INSERT INTO heroes (name, castle_id, specialization, attack, defense, power, knowledge, starting_spell) VALUES
('Лорд Хаарт', (SELECT id FROM castles WHERE name = 'Замок'), 'Рыцари', 2, 2, 1, 1, NULL),
('Сэр Маллак', (SELECT id FROM castles WHERE name = 'Замок'), 'Рыцари', 1, 1, 2, 1, NULL),
('Кристина', (SELECT id FROM castles WHERE name = 'Замок'), 'Клерики', 1, 0, 2, 2, 'Благословение'),
('Эдрик', (SELECT id FROM castles WHERE name = 'Замок'), 'Клерики', 0, 1, 2, 2, 'Благословение'),
('Рион', (SELECT id FROM castles WHERE name = 'Оплот'), 'Рейнджеры', 2, 1, 1, 1, NULL),
('Киру', (SELECT id FROM castles WHERE name = 'Оплот'), 'Рейнджеры', 1, 2, 1, 1, NULL),
('Аэрис', (SELECT id FROM castles WHERE name = 'Оплот'), 'Друиды', 0, 1, 2, 2, 'Молния'),
('Гельмут', (SELECT id FROM castles WHERE name = 'Оплот'), 'Друиды', 1, 0, 2, 2, 'Молния'),
('Сольмир', (SELECT id FROM castles WHERE name = 'Башня'), 'Алхимики', 1, 1, 2, 1, NULL),
('Айна', (SELECT id FROM castles WHERE name = 'Башня'), 'Алхимики', 1, 1, 1, 2, NULL),
('Астрал', (SELECT id FROM castles WHERE name = 'Башня'), 'Волшебники', 0, 0, 3, 2, 'Молния'),
('Халон', (SELECT id FROM castles WHERE name = 'Башня'), 'Волшебники', 0, 0, 2, 3, 'Молния'),
('Раша', (SELECT id FROM castles WHERE name = 'Инферно'), 'Демонологи', 1, 1, 2, 1, NULL),
('Мартина', (SELECT id FROM castles WHERE name = 'Инферно'), 'Демонологи', 1, 1, 1, 2, NULL),
('Ксерон', (SELECT id FROM castles WHERE name = 'Инферно'), 'Чернокнижники', 0, 1, 2, 2, 'Проклятие'),
('Аксар', (SELECT id FROM castles WHERE name = 'Инферно'), 'Чернокнижники', 1, 0, 2, 2, 'Проклятие'),
('Видаомна', (SELECT id FROM castles WHERE name = 'Некрополис'), 'Некроманты', 0, 1, 2, 2, 'Скелеты'),
('Страгос', (SELECT id FROM castles WHERE name = 'Некрополис'), 'Некроманты', 1, 0, 2, 2, 'Скелеты'),
('Моандор', (SELECT id FROM castles WHERE name = 'Некрополис'), 'Смертные лорды', 2, 1, 1, 1, NULL),
('Золтан', (SELECT id FROM castles WHERE name = 'Некрополис'), 'Смертные лорды', 1, 2, 1, 1, NULL),
('Даркон', (SELECT id FROM castles WHERE name = 'Подземелье'), 'Ведьмы', 1, 1, 2, 1, NULL),
('Джабет', (SELECT id FROM castles WHERE name = 'Подземелье'), 'Ведьмы', 1, 1, 1, 2, NULL),
('Аламар', (SELECT id FROM castles WHERE name = 'Подземелье'), 'Чародеи', 0, 0, 3, 2, 'Молния'),
('Дармун', (SELECT id FROM castles WHERE name = 'Подземелье'), 'Чародеи', 0, 0, 2, 3, 'Молния'),
('Килгор', (SELECT id FROM castles WHERE name = 'Крепость'), 'Варвары', 2, 2, 1, 0, NULL),
('Дракон', (SELECT id FROM castles WHERE name = 'Крепость'), 'Варвары', 2, 1, 1, 1, NULL),
('Вулькан', (SELECT id FROM castles WHERE name = 'Крепость'), 'Боевые маги', 1, 0, 2, 2, 'Молния'),
('Айрис', (SELECT id FROM castles WHERE name = 'Крепость'), 'Боевые маги', 0, 1, 2, 2, 'Молния'),
('Йог', (SELECT id FROM castles WHERE name = 'Цитадель'), 'Битвы', 2, 1, 1, 1, NULL),
('Греми', (SELECT id FROM castles WHERE name = 'Цитадель'), 'Битвы', 1, 2, 1, 1, NULL),
('Игнасиус', (SELECT id FROM castles WHERE name = 'Цитадель'), 'Руны', 0, 1, 2, 2, 'Молния'),
('Нейм', (SELECT id FROM castles WHERE name = 'Цитадель'), 'Руны', 1, 0, 2, 2, 'Молния'),
('Луна', (SELECT id FROM castles WHERE name = 'Убежище'), 'Элементалисты', 0, 0, 3, 2, 'Молния'),
('Бриз', (SELECT id FROM castles WHERE name = 'Убежище'), 'Элементалисты', 0, 0, 2, 3, 'Молния'),
('Грэм', (SELECT id FROM castles WHERE name = 'Убежище'), 'Планисты', 1, 1, 2, 1, NULL),
('Иона', (SELECT id FROM castles WHERE name = 'Убежище'), 'Планисты', 1, 1, 1, 2, NULL);

INSERT INTO creatures (name, level, attack, defense, damage_min, damage_max, health, speed, growth, cost_gold, cost_resource, castle_id) VALUES
('Копейщик', 1, 6, 5, 1, 3, 10, 4, 14, 60, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Лучник', 1, 6, 3, 2, 3, 10, 4, 12, 100, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Грифон', 2, 8, 8, 3, 6, 25, 6, 7, 200, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Мечник', 2, 10, 12, 6, 9, 35, 5, 4, 300, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Монах', 3, 12, 7, 10, 12, 30, 5, 4, 400, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Кавалерист', 3, 15, 15, 15, 25, 100, 7, 3, 1000, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Ангел', 4, 20, 20, 50, 50, 200, 12, 2, 3000, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Архангел', 4, 30, 30, 50, 50, 250, 18, 1, 5000, NULL, (SELECT id FROM castles WHERE name = 'Замок')),
('Кентавр', 1, 5, 3, 2, 3, 10, 6, 14, 70, NULL, (SELECT id FROM castles WHERE name = 'Оплот')),
('Эльф', 1, 9, 5, 3, 5, 15, 7, 9, 200, NULL, (SELECT id FROM castles WHERE name = 'Оплот')),
('Гном', 2, 6, 7, 2, 4, 20, 3, 8, 300, NULL, (SELECT id FROM castles WHERE name = 'Оплот')),
('Пегас', 2, 9, 8, 5, 9, 30, 8, 5, 300, NULL, (SELECT id FROM castles WHERE name = 'Оплот')),
('Дендроид-Страж', 3, 9, 12, 10, 14, 65, 3, 3, 550, NULL, (SELECT id FROM castles WHERE name = 'Оплот')),
('Единорог', 3, 15, 14, 18, 22, 90, 9, 2, 850, NULL, (SELECT id FROM castles WHERE name = 'Оплот')),
('Зеленый Дракон', 4, 18, 18, 40, 50, 180, 10, 2, 2400, '1 Драгоценный камень', (SELECT id FROM castles WHERE name = 'Оплот')),
('Золотой Дракон', 4, 27, 27, 40, 50, 200, 16, 1, 4000, '2 Драгоценных камня', (SELECT id FROM castles WHERE name = 'Оплот')),
('Гремлин', 1, 3, 3, 1, 2, 4, 4, 16, 30, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Каменный Гремлин', 1, 4, 4, 1, 2, 4, 4, 16, 40, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Голем', 2, 7, 10, 4, 5, 30, 5, 6, 150, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Железный Голем', 2, 9, 10, 4, 5, 35, 5, 6, 200, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Маг', 3, 11, 8, 7, 9, 25, 5, 4, 350, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Архимаг', 3, 12, 9, 7, 9, 30, 7, 3, 450, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Гений', 3, 12, 12, 13, 16, 40, 7, 4, 400, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Мастер Гений', 3, 12, 12, 13, 16, 40, 11, 4, 500, NULL, (SELECT id FROM castles WHERE name = 'Башня')),
('Нага', 4, 16, 13, 20, 20, 110, 7, 2, 1100, '1 Ртуть', (SELECT id FROM castles WHERE name = 'Башня')),
('Королева Наг', 4, 16, 13, 30, 30, 110, 7, 2, 1600, '1 Ртуть', (SELECT id FROM castles WHERE name = 'Башня')),
('Титан', 4, 24, 24, 40, 60, 300, 11, 1, 5000, '2 Ртути', (SELECT id FROM castles WHERE name = 'Башня')),
('Гигант', 4, 19, 19, 40, 60, 300, 7, 1, 5000, '2 Ртути', (SELECT id FROM castles WHERE name = 'Башня')),
('Имп', 1, 2, 3, 1, 2, 4, 5, 8, 50, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Бес', 1, 2, 3, 1, 2, 4, 6, 8, 60, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Гог', 2, 6, 4, 2, 4, 13, 4, 6, 125, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Магог', 2, 7, 4, 2, 4, 13, 5, 6, 175, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Адская Собака', 2, 10, 6, 2, 7, 25, 7, 5, 200, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Цербер', 2, 10, 8, 2, 7, 25, 8, 5, 250, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Демон', 3, 19, 21, 30, 40, 35, 11, 4, 250, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Рогатый Демон', 3, 19, 21, 30, 40, 40, 11, 4, 270, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Пит Лорд', 3, 13, 13, 13, 17, 45, 6, 3, 500, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Пит Фьюри', 3, 13, 13, 13, 17, 45, 7, 3, 700, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Эфрит', 4, 16, 14, 16, 24, 90, 13, 2, 900, '1 Сера', (SELECT id FROM castles WHERE name = 'Инферно')),
('Султан Эфрит', 4, 16, 14, 16, 24, 90, 13, 2, 1100, '1 Сера', (SELECT id FROM castles WHERE name = 'Инферно')),
('Дьявол', 4, 21, 18, 30, 40, 160, 11, 1, 2700, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Архидьявол', 4, 26, 28, 30, 40, 200, 17, 1, 4500, NULL, (SELECT id FROM castles WHERE name = 'Инферно')),
('Скелет', 1, 5, 4, 1, 3, 6, 4, 12, 60, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Ходячий Мертвец', 1, 5, 5, 2, 3, 6, 3, 12, 50, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Зомби', 1, 5, 5, 2, 3, 15, 4, 12, 100, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Зомби-Мутант', 1, 5, 5, 2, 3, 20, 4, 12, 125, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Призрак', 2, 3, 3, 1, 3, 5, 5, 7, 200, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Привидение', 2, 3, 3, 1, 3, 5, 7, 7, 230, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Вампир', 3, 10, 9, 5, 8, 30, 6, 4, 500, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Вампир-Лорд', 3, 10, 10, 5, 8, 40, 9, 4, 600, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Лич', 3, 13, 10, 11, 15, 30, 6, 3, 550, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Могущественный Лич', 3, 13, 10, 11, 15, 40, 7, 3, 600, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Костяной Дракон', 4, 15, 17, 25, 50, 150, 9, 2, 1800, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Призрачный Дракон', 4, 19, 17, 25, 50, 200, 14, 1, 3000, NULL, (SELECT id FROM castles WHERE name = 'Некрополис')),
('Троглодит', 1, 5, 2, 1, 3, 5, 4, 14, 50, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Инфернальный Троглодит', 1, 6, 2, 1, 3, 6, 5, 14, 65, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Гарпия', 1, 6, 6, 1, 4, 14, 6, 8, 130, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Гарпия-Ведьма', 1, 6, 6, 1, 4, 14, 9, 8, 170, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Глаз Зла', 2, 9, 7, 3, 5, 22, 4, 6, 250, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Око Зла', 2, 10, 8, 3, 5, 22, 5, 6, 280, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Медуза', 2, 10, 8, 6, 8, 25, 5, 4, 300, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Королева Медуз', 2, 10, 10, 6, 8, 30, 6, 4, 330, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Минотавр', 3, 14, 12, 12, 20, 50, 6, 3, 500, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Минотавр-Король', 3, 15, 15, 12, 20, 50, 8, 3, 575, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Мантикора', 3, 15, 13, 14, 20, 80, 7, 2, 850, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Скорпикора', 3, 16, 14, 14, 20, 80, 11, 2, 1050, NULL, (SELECT id FROM castles WHERE name = 'Подземелье')),
('Красный Дракон', 4, 19, 19, 40, 50, 180, 11, 2, 2500, '1 Сера', (SELECT id FROM castles WHERE name = 'Подземелье')),
('Черный Дракон', 4, 25, 25, 40, 50, 300, 15, 1, 4000, '2 Серы', (SELECT id FROM castles WHERE name = 'Подземелье')),
('Гоблин', 1, 4, 2, 1, 2, 5, 5, 8, 50, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Хобгоблин', 1, 5, 3, 1, 2, 5, 7, 8, 60, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Волк', 1, 8, 5, 3, 4, 10, 6, 9, 100, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Волк-Вожак', 1, 8, 5, 3, 4, 10, 7, 9, 110, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Орк', 2, 8, 4, 2, 5, 15, 4, 7, 150, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Орк-Вождь', 2, 8, 4, 2, 5, 20, 5, 7, 165, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Огр', 2, 13, 7, 6, 12, 40, 4, 4, 300, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Огр-Маг', 2, 13, 7, 6, 12, 60, 5, 4, 400, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Рока', 3, 11, 11, 6, 10, 60, 7, 3, 600, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Громовая Птица', 3, 11, 11, 6, 10, 60, 11, 3, 700, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Циклоп', 3, 16, 12, 16, 20, 70, 6, 2, 750, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Циклоп-Король', 3, 19, 13, 16, 20, 70, 8, 2, 1100, NULL, (SELECT id FROM castles WHERE name = 'Крепость')),
('Бехолдер', 4, 19, 17, 22, 28, 160, 9, 1, 3000, '1 Ртуть', (SELECT id FROM castles WHERE name = 'Крепость')),
('Злой Глаз', 4, 19, 17, 22, 28, 160, 11, 1, 3300, '1 Ртуть', (SELECT id FROM castles WHERE name = 'Крепость')),
('Гном', 1, 6, 5, 2, 4, 20, 3, 8, 120, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Боевой Гном', 1, 6, 5, 2, 4, 20, 5, 8, 150, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Гном-Разведчик', 1, 4, 4, 1, 2, 10, 5, 8, 100, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Гном-Страж', 1, 4, 4, 1, 2, 10, 5, 8, 100, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Берсерк', 2, 8, 4, 3, 5, 15, 5, 5, 150, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Берсерк-Вождь', 2, 8, 4, 3, 5, 15, 6, 5, 175, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Гном-Всадник', 2, 9, 10, 3, 5, 20, 6, 3, 200, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Гном-Всадник-Вождь', 2, 9, 10, 3, 5, 20, 7, 3, 250, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Железный Голем', 2, 9, 10, 4, 5, 35, 5, 6, 200, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Стальной Голем', 2, 10, 11, 4, 5, 45, 6, 6, 250, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Маг', 3, 11, 8, 7, 9, 25, 5, 4, 350, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Архимаг', 3, 12, 9, 7, 9, 30, 7, 3, 450, NULL, (SELECT id FROM castles WHERE name = 'Цитадель')),
('Дракон', 4, 18, 18, 40, 50, 180, 11, 2, 2000, '1 Ртуть', (SELECT id FROM castles WHERE name = 'Цитадель')),
('Алмазный Дракон', 4, 18, 18, 40, 50, 200, 16, 1, 3000, '2 Ртути', (SELECT id FROM castles WHERE name = 'Цитадель')),
('Спрайт', 1, 2, 2, 1, 2, 3, 7, 20, 25, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Энергетический Элементаль', 1, 2, 2, 1, 2, 3, 8, 20, 30, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Элементаль Воздуха', 1, 9, 9, 2, 8, 25, 8, 6, 250, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Штормовой Элементаль', 1, 9, 9, 2, 8, 25, 8, 6, 275, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Элементаль Воды', 2, 8, 10, 3, 7, 30, 5, 6, 300, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Ледяной Элементаль', 2, 8, 10, 3, 7, 30, 6, 6, 375, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Элементаль Огня', 2, 10, 8, 4, 6, 35, 6, 6, 350, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Энергетический Элементаль Огня', 2, 12, 8, 4, 6, 35, 8, 6, 400, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Элементаль Земли', 3, 10, 10, 4, 8, 40, 4, 4, 400, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Магма Элементаль', 3, 11, 11, 4, 8, 50, 6, 4, 500, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Психический Элементаль', 3, 15, 13, 10, 20, 75, 7, 3, 750, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Магический Элементаль', 3, 15, 13, 15, 25, 80, 9, 3, 800, NULL, (SELECT id FROM castles WHERE name = 'Убежище')),
('Огненная Птица', 4, 18, 18, 30, 40, 150, 15, 2, 1500, '1 Сера', (SELECT id FROM castles WHERE name = 'Убежище')),
('Феникс', 4, 21, 18, 30, 40, 200, 21, 1, 2000, '1 Сера', (SELECT id FROM castles WHERE name = 'Убежище'));

INSERT INTO artifacts (name, slot, description, attack_bonus, defense_bonus, power_bonus, knowledge_bonus, rarity) VALUES
('Меч Холодной Смерти', 'Оружие', 'Увеличивает атаку на 3', 3, 0, 0, 0, 'Редкий'),
('Меч Огня', 'Оружие', 'Увеличивает атаку на 2', 2, 0, 0, 0, 'Обычный'),
('Меч Ледяного Пламени', 'Оружие', 'Увеличивает атаку на 4', 4, 0, 0, 0, 'Очень редкий'),
('Щит Отражения', 'Щит', 'Увеличивает защиту на 3', 0, 3, 0, 0, 'Редкий'),
('Щит Дракона', 'Щит', 'Увеличивает защиту на 2', 0, 2, 0, 0, 'Обычный'),
('Кольцо Жизни', 'Кольцо', 'Увеличивает здоровье героя', 0, 0, 0, 0, 'Обычный'),
('Кольцо Маны', 'Кольцо', 'Увеличивает ману героя', 0, 0, 0, 0, 'Обычный'),
('Амулет Маны', 'Амулет', 'Увеличивает силу на 2', 0, 0, 2, 0, 'Редкий'),
('Амулет Знания', 'Амулет', 'Увеличивает знание на 2', 0, 0, 0, 2, 'Редкий'),
('Шлем Дракона', 'Голова', 'Увеличивает защиту на 1', 0, 1, 0, 0, 'Обычный'),
('Корона Повелителя', 'Голова', 'Увеличивает все характеристики на 1', 1, 1, 1, 1, 'Очень редкий'),
('Доспех Дракона', 'Торс', 'Увеличивает защиту на 2', 0, 2, 0, 0, 'Редкий'),
('Плащ Невидимости', 'Плащ', 'Позволяет герою быть невидимым', 0, 0, 0, 0, 'Очень редкий'),
('Сапоги Скорости', 'Ноги', 'Увеличивает скорость передвижения', 0, 0, 0, 0, 'Обычный'),
('Перчатки Силы', 'Руки', 'Увеличивает атаку на 1', 1, 0, 0, 0, 'Обычный'),
('Меч Армагеддона', 'Оружие', 'Легендарный меч, увеличивает атаку на 6', 6, 0, 0, 0, 'Легендарный'),
('Щит Непобедимости', 'Щит', 'Легендарный щит, увеличивает защиту на 6', 0, 6, 0, 0, 'Легендарный'),
('Кольцо Всеведения', 'Кольцо', 'Легендарное кольцо, увеличивает знание на 6', 0, 0, 0, 6, 'Легендарный'),
('Амулет Бессмертия', 'Амулет', 'Легендарный амулет, увеличивает силу на 6', 0, 0, 6, 0, 'Легендарный');

INSERT INTO spells (name, school, level, cost, description) VALUES
('Молния', 'Воздух', 1, 5, 'Наносит урон молнией'),
('Цепная Молния', 'Воздух', 3, 15, 'Молния, которая поражает несколько целей'),
('Метеоритный Дождь', 'Земля', 4, 15, 'Мощное заклинание земли'),
('Огненный Шар', 'Огонь', 2, 8, 'Взрыв огня, наносящий урон'),
('Взрыв', 'Огонь', 3, 10, 'Мощный взрыв огня'),
('Армагеддон', 'Огонь', 4, 24, 'Самое мощное заклинание огня'),
('Ледяная Стрела', 'Вода', 1, 4, 'Наносит урон льдом'),
('Ледяное Кольцо', 'Вода', 3, 10, 'Ледяное кольцо, поражающее всех врагов'),
('Благословение', 'Все', 1, 3, 'Увеличивает минимальный и максимальный урон'),
('Проклятие', 'Все', 1, 3, 'Уменьшает минимальный и максимальный урон'),
('Скелеты', 'Все', 1, 4, 'Призывает скелетов'),
('Воскрешение', 'Все', 4, 15, 'Воскрешает павших существ'),
('Ускорение', 'Воздух', 1, 5, 'Увеличивает скорость отряда'),
('Замедление', 'Вода', 1, 5, 'Уменьшает скорость отряда'),
('Щит', 'Вода', 1, 5, 'Увеличивает защиту отряда'),
('Камень Кожи', 'Земля', 1, 5, 'Увеличивает защиту отряда'),
('Берсерк', 'Огонь', 2, 6, 'Заставляет врага атаковать своих'),
('Слепота', 'Земля', 2, 6, 'Ослепляет отряд врага'),
('Паралич', 'Земля', 3, 8, 'Парализует отряд врага'),
('Воскрешение Истинное', 'Все', 5, 20, 'Мощное воскрешение павших существ');

INSERT INTO skills (name, description, category) VALUES
('Атака', 'Увеличивает атаку героя и его отрядов', 'Боевая'),
('Защита', 'Увеличивает защиту героя и его отрядов', 'Боевая'),
('Стрельба', 'Увеличивает урон стрелковых отрядов', 'Боевая'),
('Логистика', 'Увеличивает скорость передвижения по карте', 'Приключенческая'),
('Разведка', 'Увеличивает радиус обзора на карте', 'Приключенческая'),
('Навигация', 'Увеличивает скорость передвижения по воде', 'Приключенческая'),
('Дипломатия', 'Позволяет нанимать нейтральных существ', 'Приключенческая'),
('Эстимация', 'Позволяет видеть примерную стоимость артефактов', 'Приключенческая'),
('Ученый', 'Позволяет изучать заклинания у других героев', 'Магическая'),
('Понимание', 'Увеличивает эффективность магии', 'Магическая'),
('Мистицизм', 'Увеличивает скорость восстановления маны', 'Магическая'),
('Мудрость', 'Позволяет изучать заклинания высокого уровня', 'Магическая'),
('Некромантия', 'Позволяет воскрешать убитых врагов как скелетов', 'Магическая'),
('Воздушная Магия', 'Увеличивает эффективность заклинаний воздуха', 'Магическая'),
('Земляная Магия', 'Увеличивает эффективность заклинаний земли', 'Магическая'),
('Огненная Магия', 'Увеличивает эффективность заклинаний огня', 'Магическая'),
('Водная Магия', 'Увеличивает эффективность заклинаний воды', 'Магическая'),
('Лидерство', 'Увеличивает мораль отрядов', 'Вспомогательная'),
('Удача', 'Увеличивает удачу отрядов', 'Вспомогательная'),
('Сопротивление', 'Увеличивает сопротивление магии', 'Вспомогательная'),
('Баллистика', 'Увеличивает урон катапульты', 'Вспомогательная'),
('Первая Помощь', 'Позволяет лечить отряды в бою', 'Вспомогательная');

CREATE INDEX idx_heroes_castle ON heroes(castle_id);
CREATE INDEX idx_creatures_castle ON creatures(castle_id);
CREATE INDEX idx_creatures_level ON creatures(level);
CREATE INDEX idx_spells_school ON spells(school);
CREATE INDEX idx_spells_level ON spells(level);
CREATE INDEX idx_artifacts_slot ON artifacts(slot);
CREATE INDEX idx_artifacts_rarity ON artifacts(rarity);

